# Generated by Django 5.2.11 on 2026-02-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField()),
                ('floorNo', models.IntegerField()),
                ('nearWashroom', models.BooleanField(default=False)),
            ],
        ),
    ]
